name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify slack starting deploy
      if: success()
      id: slackNotify
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEEEPLOY_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: releases
        status: STARTING
        color: warning
    - name: Yarn Install
      run: |
        yarn install
    - name: Yarn Build
      env:
        CI: ""
      run: |
        yarn build:prod
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build"
    - name: Notify slack on deploy success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEEEPLOY_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slackNotify.outputs.message_id }}
        channel: releases
        status: SUCCESS
        color: good
    - name: Notify slack on deploy failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEEEPLOY_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: releases
        status: FAILED
        color: danger
